version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ember-power-select
    versions:
    - 4.1.0
    - 4.1.2
    - 4.1.3
  - dependency-name: ember-data
    versions:
    - 3.24.0
    - 3.25.0
  - dependency-name: ember-sortable
    versions:
    - 2.2.2
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: jquery
    versions:
    - 3.5.1
